/**
 * Local account storage: sign-up, sign-in, sessions.
 *
 * A port of backend/auth.py. Scope, stated plainly: this is real
 * authentication for a locally-run tool, not a production identity system.
 * Passwords are hashed with scrypt and a per-user salt (never stored or logged
 * in plaintext), sessions are opaque random tokens with an expiry, and
 * everything lives in the same database as the rest of the app.
 *
 * What it deliberately does NOT do: email verification, password reset, rate
 * limiting beyond a simple attempt counter, OAuth, or 2FA. Do not put this on
 * the public internet as-is.
 *
 * Deploying it on Vercel does put it on the public internet. That was the
 * Python's warning and it still holds - more so, because a hosted URL is
 * reachable by anyone who finds it.
 */

import crypto from 'node:crypto'
import { promisify } from 'node:util'
import { query, run, exec, insertReturningId, DIALECT } from './db-driver.js'

const scrypt = promisify(crypto.scrypt)

// scrypt parameters. N=2**14 keeps sign-in near ~100 ms - slow enough to be
// costly to brute force, fast enough to feel instant. Unchanged from the
// Python, so hashes written by either implementation verify under the other.
const SCRYPT_N = 2 ** 14
const SCRYPT_R = 8
const SCRYPT_P = 1
const KEY_LEN = 64
const SALT_BYTES = 16

export const SESSION_DAYS = 14
export const MIN_PASSWORD = 8
export const MAX_PASSWORD = 200          // scrypt on an unbounded string is a DoS vector
const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/

// AUTOINCREMENT is SQLite's spelling and Postgres rejects it outright; the
// generated-identity syntax has to be written per dialect.
const SCHEMA = (d) => {
  const PK = d === 'postgres'
    ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    : 'INTEGER PRIMARY KEY AUTOINCREMENT'
  const BLOB = d === 'postgres' ? 'BYTEA' : 'BLOB'
  return `
CREATE TABLE IF NOT EXISTS users (
    id          ${PK},
    email       TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    salt        ${BLOB} NOT NULL,
    password_hash ${BLOB} NOT NULL,
    created_at  TEXT NOT NULL,
    last_login  TEXT
);
CREATE TABLE IF NOT EXISTS sessions (
    token       TEXT PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    created_at  TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
`
}

/** Raised for anything the caller should see as a 4xx. */
export class AuthError extends Error {
  constructor(message, status = 400) {
    super(message)
    this.name = 'AuthError'
    this.status = status
  }
}

export async function init() {
  await exec(SCHEMA(DIALECT))
}

const nowDate = () => new Date()
const iso = (dt) => dt.toISOString().replace(/\.\d{3}Z$/, '+00:00')

function hashPassword(password, salt) {
  // maxmem must be raised explicitly: scrypt needs ~128*N*r bytes, which is
  // 16 MB at these parameters, and Node's default cap sits just above that.
  // Without it the call fails only on the real parameters, never in a smoke
  // test with smaller ones.
  return scrypt(Buffer.from(password, 'utf-8'), salt, KEY_LEN, {
    N: SCRYPT_N, r: SCRYPT_R, p: SCRYPT_P, maxmem: 256 * 1024 * 1024,
  })
}

/** Normalise whatever the driver hands back for a BLOB into a Buffer. */
const toBuf = (v) => (Buffer.isBuffer(v) ? v : Buffer.from(v))

// ---------------------------------------------------------------- validation
function cleanEmail(email) {
  const e = (email ?? '').trim().toLowerCase()
  if (!EMAIL_RE.test(e)) throw new AuthError('That does not look like a valid email address.', 422)
  if (e.length > 254) throw new AuthError('That email address is too long.', 422)
  return e
}

function cleanName(name) {
  const n = (name ?? '').trim()
  if (n.length < 2) throw new AuthError('Please enter your name (at least 2 characters).', 422)
  if (n.length > 80) throw new AuthError('That name is too long.', 422)
  return n
}

function checkPassword(password) {
  if (!password || password.length < MIN_PASSWORD) {
    throw new AuthError(`Password must be at least ${MIN_PASSWORD} characters.`, 422)
  }
  if (password.length > MAX_PASSWORD) {
    throw new AuthError(`Password must be under ${MAX_PASSWORD} characters.`, 422)
  }
  // Python's str.isdigit() and str.isalpha() are Unicode-aware, so the
  // equivalent regexes are too - an all-Cyrillic password is as weak as an
  // all-ASCII one and must be rejected the same way.
  if (/^\p{Nd}+$/u.test(password) || /^\p{L}+$/u.test(password)) {
    throw new AuthError('Use a mix of letters and numbers.', 422)
  }
  return password
}

// --------------------------------------------------------------------- users
export async function signUp(email, name, password) {
  const e = cleanEmail(email)
  const n = cleanName(name)
  checkPassword(password)

  const salt = crypto.randomBytes(SALT_BYTES)
  const digest = await hashPassword(password, salt)

  const existing = await query('SELECT id FROM users WHERE email = ?', [e])
  if (existing.length) throw new AuthError('An account with that email already exists.', 409)

  const userId = await insertReturningId(
    `INSERT INTO users (email, name, salt, password_hash, created_at)
     VALUES (?,?,?,?,?)`,
    [e, n, salt, digest, iso(nowDate())],
  )

  return issueSession(userId, e, n)
}

export async function signIn(email, password) {
  const e = cleanEmail(email)

  const rows = await query(
    'SELECT id, email, name, salt, password_hash FROM users WHERE email = ?', [e],
  )
  const row = rows[0] ?? null

  // Hash even when the user does not exist, so a missing account and a wrong
  // password take the same time and cannot be told apart by timing.
  const salt = row ? toBuf(row.salt) : crypto.randomBytes(SALT_BYTES)
  const expected = row ? toBuf(row.password_hash) : crypto.randomBytes(KEY_LEN)
  const candidate = await hashPassword(password ?? '', salt)

  // timingSafeEqual throws on a length mismatch rather than returning false,
  // which would itself leak through an exception path, so lengths are checked
  // first and the comparison only runs on equal-length buffers.
  const ok = row
    && candidate.length === expected.length
    && crypto.timingSafeEqual(candidate, expected)

  if (!ok) throw new AuthError('Incorrect email or password.', 401)

  await run('UPDATE users SET last_login = ? WHERE id = ?', [iso(nowDate()), row.id])

  return issueSession(row.id, row.email, row.name)
}

async function issueSession(userId, email, name) {
  // 32 random bytes, base64url - the same shape and entropy as Python's
  // secrets.token_urlsafe(32).
  const token = crypto.randomBytes(32).toString('base64url')
  const now = nowDate()
  const expires = new Date(now.getTime() + SESSION_DAYS * 86400_000)

  await run(
    'INSERT INTO sessions (token, user_id, created_at, expires_at) VALUES (?,?,?,?)',
    [token, userId, iso(now), iso(expires)],
  )

  return {
    token,
    expires_at: iso(expires),
    user: { id: Number(userId), email, name },
  }
}

/** Resolve a session token, or null if missing, unknown or expired. */
export async function currentUser(token) {
  if (!token) return null

  const rows = await query(
    `SELECT s.expires_at, u.id, u.email, u.name, u.created_at
     FROM sessions s JOIN users u ON u.id = s.user_id
     WHERE s.token = ?`,
    [token],
  )
  const row = rows[0]
  if (!row) return null

  if (new Date(row.expires_at) < nowDate()) {
    await signOut(token)
    return null
  }

  return {
    id: Number(row.id), email: row.email,
    name: row.name, created_at: row.created_at,
  }
}

export async function signOut(token) {
  if (!token) return false
  const { changes } = await run('DELETE FROM sessions WHERE token = ?', [token])
  return changes > 0
}

export async function purgeExpired() {
  const { changes } = await run('DELETE FROM sessions WHERE expires_at < ?', [iso(nowDate())])
  return changes
}

export async function userCount() {
  const [{ c }] = await query('SELECT COUNT(*) c FROM users')
  return Number(c)
}
